name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run Dependency Scan
        run: npm audit --audit-level=high
