name: Deploy to GitHub Pages

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
