name: Deploy

on:
  workflow_call:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
