name: Lighthouse Test

on:
  workflow_call:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ secrets.SITE_URL }}
          uploadArtifacts: true
          temporaryPublicStorage: true
